Implement csv class maps for contact and organization
VirtoCommerce/vc-module-customer-export-import pull request #11
Opened 2021-05-20 10:08 UTC by trueboroda

2021-05-20 11:48 UTC, asvishnyakov commented on tests/VirtoCommerce.CustomerExportImportModule.Tests/CsvClassMapsTest.cs
> +            sw.Dispose();
I think Dispose should use Flush and Close internally

2021-05-20 14:17 UTC, mvktsk commented
Review task https://virtocommerce.atlassian.net/browse/VP-7416 has been created

2021-05-21 07:25 UTC, asvishnyakov requested changes

2021-05-21 07:25 UTC, asvishnyakov commented on src/VirtoCommerce.CustomerExportImportModule.Core/Models/ExportableContact.cs
> +            AccountEmail = account?.StoreId;
Account.Email

2021-05-21 07:25 UTC, asvishnyakov commented on src/VirtoCommerce.CustomerExportImportModule.Core/Models/ExportableContact.cs
> +            AddressCountry = address?.RegionName;
Country, not RegionName

2021-05-21 07:25 UTC, asvishnyakov commented on src/VirtoCommerce.CustomerExportImportModule.Core/Models/ExportableOrganization.cs
> +            AddressCountry = address?.RegionName;
Country, not RegionName

2021-05-21 07:28 UTC, asvishnyakov requested changes

2021-05-21 07:28 UTC, asvishnyakov commented on src/VirtoCommerce.CustomerExportImportModule.Data/ExportImport/GenericClassMap.cs
> +                    csvPropertyMap.Data.Index = ++columnIndex;
I'll prefer to write `var columnIndex = MemberMaps.Count` and `csvPropertyMap.DataIndex = columnIndex++`

2021-05-21 07:28 UTC, asvishnyakov commented on src/VirtoCommerce.CustomerExportImportModule.Data/VirtoCommerce.CustomerExportImportModule.Data.csproj
> +        <PackageReference Include="VirtoCommerce.CustomerModule.Core" Version="3.28.0" />
Core already has reference, not this is redundant

2021-05-21 07:29 UTC, asvishnyakov requested changes
Please add tests for dictionary & multivalue dynamic properties, address mapping, and joining on enumerables.

2021-05-21 08:37 UTC, asvishnyakov approved these changes

2021-05-21 08:53 UTC, merged