VDS-1749: Frontend for export
VirtoCommerce/vc-module-customer-export-import pull request #16
Opened 2021-05-24 14:48 UTC by Pav-el

Description: 

--

QA-test: 

Demo-test: 

Download artifact URL:

2021-05-24 14:51 UTC, Pav-el commented
There is no callback function in export dialog implemented.

2021-05-24 15:03 UTC, trueboroda approved these changes

2021-05-25 06:45 UTC, trueboroda requested changes

2021-05-25 06:45 UTC, trueboroda commented on src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/module.js
> +                                    showExportDialog(contactsCount, organizationsCount);
where is there the running of the export job via API?

2021-05-25 06:49 UTC, trueboroda approved these changes

2021-05-25 06:53 UTC, pushnitsa commented on .gitignore
> +launchSettings.json
Why we ignored launchSettings.json?

2021-05-25 14:03 UTC, ilyawzrd approved these changes

2021-05-25 14:35 UTC, merged