VDS-1360: Development import statistics for UI
VirtoCommerce/vc-module-customer-export-import pull request #30
Opened 2021-06-03 16:00 UTC by Pav-el

Description: 

--

QA-test: VDS-1361

Demo-test: VDS-1362

Download artifact URL:

2021-06-04 07:32 UTC, pushnitsa commented on src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/blades/import-processing.tpl.html
> +                            <p class="list-item-title">Errors</p>
Add localization please

2021-06-04 08:55 UTC, ilyawzrd approved these changes

2021-06-04 09:44 UTC, pushnitsa approved these changes

2021-06-07 08:36 UTC, asvishnyakov requested changes

2021-06-07 08:36 UTC, asvishnyakov commented on src/VirtoCommerce.CustomerExportImportModule.Web/Scripts/blades/import-processing.tpl.html
> +                <div class="block progress-wrap" ng-if="blade.notification.created || blade.notification.finished">
Here and below: why these `if` exists? It hide values if they have 0. Check as `!!x` instead if you need to hide them when undefined

2021-06-08 07:55 UTC, asvishnyakov approved these changes

2021-06-08 08:51 UTC, trueboroda approved these changes

2021-06-10 06:24 UTC, pushnitsa requested changes

2021-06-10 06:24 UTC, pushnitsa commented on src/VirtoCommerce.CustomerExportImportModule.Web/module.manifest
> +        <dependency id="VirtoCommerce.DemoSolutionFeatures" version="1.12.0" />
Import module shouldn't depend on demo modules.

2021-06-10 10:27 UTC, trueboroda approved these changes

2021-06-10 10:29 UTC, asvishnyakov approved these changes

2021-06-10 10:33 UTC, pushnitsa approved these changes

2021-06-10 11:59 UTC, merged