VDS-2022: Add 'Emails' column to import/export
VirtoCommerce/vc-module-customer-export-import pull request #41
Opened 2021-06-29 14:20 UTC by ilyawzrd

2021-06-29 14:38 UTC, pushnitsa approved these changes

2021-06-30 07:06 UTC, asvishnyakov requested changes

2021-06-30 07:06 UTC, asvishnyakov commented on src/VirtoCommerce.CustomerExportImportModule.Core/Models/CsvOrganization.cs
> +            target.Emails = string.IsNullOrEmpty(Emails) ? null : Emails.Split(", ");
Replace with `.Split(',').Select(phone => phone.Trim()).ToList()`

2021-06-30 07:06 UTC, asvishnyakov commented on src/VirtoCommerce.CustomerExportImportModule.Core/Models/CsvContact.cs
> +            target.Emails = string.IsNullOrEmpty(Emails) ? null : Emails.Split(", ");
Replace with `.Split(',').Select(phone => phone.Trim()).ToList()`

2021-06-30 07:32 UTC, ilyawzrd commented on src/VirtoCommerce.CustomerExportImportModule.Core/Models/CsvOrganization.cs
> +            target.Emails = string.IsNullOrEmpty(Emails) ? null : Emails.Split(", ");
done

2021-06-30 07:32 UTC, ilyawzrd commented on src/VirtoCommerce.CustomerExportImportModule.Core/Models/CsvContact.cs
> +            target.Emails = string.IsNullOrEmpty(Emails) ? null : Emails.Split(", ");
done

2021-06-30 09:14 UTC, asvishnyakov approved these changes

2021-06-30 10:33 UTC, asvishnyakov approved these changes

2021-06-30 16:18 UTC, asvishnyakov approved these changes

2021-07-01 08:12 UTC, merged